site_url: https://nextstop-car-reservations/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$'],
            }

  - name: 'car'
    label: 'Car'
    folder: 'assets/content/cars'
    create: true
    format: 'json'
    fields: 
      - {label: 'VIN', name: 'vin', widget: 'string'}
      - {label: 'Producent', name: 'brand', widget: 'string'}
      - {label: 'Model', name: 'model', widget: 'string'}
      - {label: 'Segment', 
         name: 'segment', 
         widget: 'select',
         options: ['A','B','C','D','E','F']
      }
      - {
          label: 'Skrzynia biegów', 
          name: 'transmission', 
          widget: 'select', 
          options: ['Automatyczna', 'Manualna']
        }
      - {
          label: 'Rodzaj silnika', 
          name: 'engineType',
          widget: 'select', 
          options: ['Benzyna', 'Diesel', 'Elektryczny', 'Hybryda']
        }
      - {label: 'Liczba miejsc', name: 'seats', widget: 'number', value_type: 'int'}
      - {label: 'Pojemność bagażnika', name: 'trunkCapacity', widget: 'number', value_type: 'int'}
      - {label: 'Cena', name: 'price', widget: 'number', value_type: 'float'}
      - {label: 'Zdjęcie', name: 'img', widget: 'image'}
      - {
          label: 'Lokalizacje', 
          name: 'locations', 
          widget: 'list', 
          summary: '{{fields.location}}', 
          field: {
            label: 'Lokalizacja', 
            name: 'location', 
            widget: 'string'
          }
        }